# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=40)),
                ('batch_job_id', models.CharField(max_length=200)),
                ('batch_job_create', models.DateTimeField()),
                ('batch_job_last_update', models.DateTimeField()),
                ('commit_author', models.CharField(max_length=128)),
                ('commit_message', models.CharField(max_length=1024)),
                ('commit_date', models.DateTimeField()),
                ('commit_url', models.CharField(max_length=1024)),
                ('download_url', models.CharField(max_length=2048)),
                ('ignore', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morocco.Snapshot')),
            ],
        ),
    ]
