# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morocco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='batch_job_create',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='batch_job_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='batch_job_last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='download_url',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
